// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5yg0KlCDOmrDQ8hBUn3YaWC3NDFvwFdY',
    appId: '1:351592891493:web:5b40f4ea6a24aa78ecf28c',
    messagingSenderId: '351592891493',
    projectId: 'gasolinemanager-b9949',
    authDomain: 'gasolinemanager-b9949.firebaseapp.com',
    storageBucket: 'gasolinemanager-b9949.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4HbJ6zHukJuSEdm8CJoSk7FVIbeBQHNw',
    appId: '1:351592891493:android:12f6ccb66e3273e3ecf28c',
    messagingSenderId: '351592891493',
    projectId: 'gasolinemanager-b9949',
    storageBucket: 'gasolinemanager-b9949.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0XBVbnswri3l6zoAF8-hWL78nX0bOtho',
    appId: '1:351592891493:ios:b528cc60306dfa7decf28c',
    messagingSenderId: '351592891493',
    projectId: 'gasolinemanager-b9949',
    storageBucket: 'gasolinemanager-b9949.firebasestorage.app',
    iosBundleId: 'com.example.atividadeProva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0XBVbnswri3l6zoAF8-hWL78nX0bOtho',
    appId: '1:351592891493:ios:b528cc60306dfa7decf28c',
    messagingSenderId: '351592891493',
    projectId: 'gasolinemanager-b9949',
    storageBucket: 'gasolinemanager-b9949.firebasestorage.app',
    iosBundleId: 'com.example.atividadeProva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5yg0KlCDOmrDQ8hBUn3YaWC3NDFvwFdY',
    appId: '1:351592891493:web:a1ca0ea38712c888ecf28c',
    messagingSenderId: '351592891493',
    projectId: 'gasolinemanager-b9949',
    authDomain: 'gasolinemanager-b9949.firebaseapp.com',
    storageBucket: 'gasolinemanager-b9949.firebasestorage.app',
  );
}
